

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(900, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(900, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/dana_logo.webp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(50, 30))
        self.Body = QtWidgets.QWidget(MainWindow)
        self.Body.setObjectName("Body")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Body)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 901, 801))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.LoginLayout = QtWidgets.QGroupBox(self.loginPage)
        self.LoginLayout.setEnabled(True)
        self.LoginLayout.setGeometry(QtCore.QRect(0, 0, 901, 801))
        self.LoginLayout.setStyleSheet("background-color: rgb(125, 132, 178);")
        self.LoginLayout.setObjectName("LoginLayout")
        self.Header = QtWidgets.QFrame(self.LoginLayout)
        self.Header.setGeometry(QtCore.QRect(0, 0, 901, 101))
        self.Header.setStyleSheet("background-color: rgb(46, 41, 78);")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.Header_2 = QtWidgets.QFrame(self.Header)
        self.Header_2.setGeometry(QtCore.QRect(480, 80, 901, 101))
        self.Header_2.setStyleSheet("background-color: rgb(46, 41, 78);")
        self.Header_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header_2.setObjectName("Header_2")
        self.Logo_2 = QtWidgets.QLabel(self.Header_2)
        self.Logo_2.setGeometry(QtCore.QRect(40, 20, 111, 61))
        self.Logo_2.setStyleSheet("background-image: url(:/Icon/dana_logo.webp);")
        self.Logo_2.setText("")
        self.Logo_2.setPixmap(QtGui.QPixmap(":/Icon/dana_logo.webp"))
        self.Logo_2.setScaledContents(True)
        self.Logo_2.setObjectName("Logo_2")
        self.loginBody = QtWidgets.QGraphicsView(self.LoginLayout)
        self.loginBody.setGeometry(QtCore.QRect(0, 150, 901, 401))
        self.loginBody.setStyleSheet("border-image: url(:/Body/body.png);")
        self.loginBody.setObjectName("loginBody")
        self.loginPanel = QtWidgets.QFrame(self.LoginLayout)
        self.loginPanel.setGeometry(QtCore.QRect(610, 190, 261, 321))
        self.loginPanel.setStyleSheet("background-color: rgb(138, 225, 252);")
        self.loginPanel.setFrameShape(QtWidgets.QFrame.Panel)
        self.loginPanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.loginPanel.setLineWidth(5)
        self.loginPanel.setObjectName("loginPanel")
        self.loginIcon = QtWidgets.QLabel(self.loginPanel)
        self.loginIcon.setGeometry(QtCore.QRect(90, 20, 61, 61))
        self.loginIcon.setStyleSheet("background-image: url(:/loginIcon/Resources/login.png);\n"
"background-color: rgb(138, 225, 252);")
        self.loginIcon.setText("")
        self.loginIcon.setPixmap(QtGui.QPixmap(":/loginIcon/Resources/login.png"))
        self.loginIcon.setScaledContents(True)
        self.loginIcon.setObjectName("loginIcon")
        self.label = QtWidgets.QLabel(self.loginPanel)
        self.label.setGeometry(QtCore.QRect(90, 90, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.loginPanel)
        self.label_2.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.userInput = QtWidgets.QLineEdit(self.loginPanel)
        self.userInput.setGeometry(QtCore.QRect(100, 141, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.userInput.setFont(font)
        self.userInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.userInput.setObjectName("userInput")
        self.label_3 = QtWidgets.QLabel(self.loginPanel)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.pswdInput = QtWidgets.QLineEdit(self.loginPanel)
        self.pswdInput.setGeometry(QtCore.QRect(100, 180, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.pswdInput.setFont(font)
        self.pswdInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pswdInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pswdInput.setObjectName("pswdInput")
        self.label_4 = QtWidgets.QLabel(self.loginPanel)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.loginBtn = QtWidgets.QPushButton(self.loginPanel)
        self.loginBtn.setGeometry(QtCore.QRect(90, 250, 93, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.loginBtn.setFont(font)
        self.loginBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.loginBtn.setObjectName("loginBtn")
        self.frame_6 = QtWidgets.QFrame(self.LoginLayout)
        self.frame_6.setGeometry(QtCore.QRect(0, 650, 901, 161))
        self.frame_6.setStyleSheet("background-color: rgb(46, 41, 78);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.stackedWidget.addWidget(self.loginPage)
        self.loadPage = QtWidgets.QWidget()
        self.loadPage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.loadPage.setObjectName("loadPage")
        self.label_5 = QtWidgets.QLabel(self.loadPage)
        self.label_5.setGeometry(QtCore.QRect(110, 20, 591, 551))
        self.label_5.setStyleSheet("background-image: url(:/load/Resources/load.gif);")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/load/Resources/load.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.loadPage)
        self.dashboardPage = QtWidgets.QWidget()
        self.dashboardPage.setObjectName("dashboardPage")
        self.frame = QtWidgets.QFrame(self.dashboardPage)
        self.frame.setGeometry(QtCore.QRect(0, -10, 901, 801))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: rgb(6, 118, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(630, 20, 81, 81))
        self.label_6.setStyleSheet("background-image: url(:/loginLogo2/Resources/login.jpg);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/loginLogo2/Resources/login.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.dashUserNameText = QtWidgets.QLabel(self.frame)
        self.dashUserNameText.setGeometry(QtCore.QRect(730, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dashUserNameText.setFont(font)
        self.dashUserNameText.setStyleSheet("color: rgb(255, 255, 255);")
        self.dashUserNameText.setObjectName("dashUserNameText")
        self.dashDateText = QtWidgets.QLabel(self.frame)
        self.dashDateText.setGeometry(QtCore.QRect(730, 50, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.dashDateText.setFont(font)
        self.dashDateText.setStyleSheet("color: rgb(255, 255, 255);")
        self.dashDateText.setObjectName("dashDateText")
        self.dashTimeText = QtWidgets.QLabel(self.frame)
        self.dashTimeText.setGeometry(QtCore.QRect(730, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashTimeText.setFont(font)
        self.dashTimeText.setStyleSheet("color: rgb(255, 255, 255);")
        self.dashTimeText.setObjectName("dashTimeText")
        self.titleText = QtWidgets.QLabel(self.frame)
        self.titleText.setGeometry(QtCore.QRect(50, 30, 461, 71))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.titleText.setFont(font)
        self.titleText.setStyleSheet("color: rgb(255, 255, 255);")
        self.titleText.setObjectName("titleText")
        self.dashBtn1 = QtWidgets.QPushButton(self.frame)
        self.dashBtn1.setGeometry(QtCore.QRect(50, 310, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dashBtn1.setFont(font)
        self.dashBtn1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.dashBtn1.setObjectName("dashBtn1")
        self.dashBtn2 = QtWidgets.QPushButton(self.frame)
        self.dashBtn2.setGeometry(QtCore.QRect(50, 230, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dashBtn2.setFont(font)
        self.dashBtn2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.dashBtn2.setObjectName("dashBtn2")
        self.dashBtn3 = QtWidgets.QPushButton(self.frame)
        self.dashBtn3.setGeometry(QtCore.QRect(50, 390, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dashBtn3.setFont(font)
        self.dashBtn3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.dashBtn3.setObjectName("dashBtn3")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(600, 590, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(600, 640, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.rfidStatLabel = QtWidgets.QLabel(self.frame)
        self.rfidStatLabel.setGeometry(QtCore.QRect(760, 590, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rfidStatLabel.setFont(font)
        self.rfidStatLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.rfidStatLabel.setObjectName("rfidStatLabel")
        self.weighScaleStatLabel = QtWidgets.QLabel(self.frame)
        self.weighScaleStatLabel.setGeometry(QtCore.QRect(760, 680, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.weighScaleStatLabel.setFont(font)
        self.weighScaleStatLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.weighScaleStatLabel.setObjectName("weighScaleStatLabel")
        self.dashLogoutBtn = QtWidgets.QPushButton(self.frame)
        self.dashLogoutBtn.setGeometry(QtCore.QRect(630, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashLogoutBtn.setFont(font)
        self.dashLogoutBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.dashLogoutBtn.setObjectName("dashLogoutBtn")
        self.dashReconnectBtn = QtWidgets.QPushButton(self.frame)
        self.dashReconnectBtn.setGeometry(QtCore.QRect(600, 740, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dashReconnectBtn.setFont(font)
        self.dashReconnectBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(255, 0, 0);\n"
"background-color: rgb(101, 116, 58);")
        self.dashReconnectBtn.setObjectName("dashReconnectBtn")
        self.dashBrowseBtn1 = QtWidgets.QPushButton(self.frame)
        self.dashBrowseBtn1.setGeometry(QtCore.QRect(790, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dashBrowseBtn1.setFont(font)
        self.dashBrowseBtn1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.dashBrowseBtn1.setObjectName("dashBrowseBtn1")
        self.dashFileLabel1 = QtWidgets.QLabel(self.frame)
        self.dashFileLabel1.setGeometry(QtCore.QRect(630, 230, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashFileLabel1.setFont(font)
        self.dashFileLabel1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 127);")
        self.dashFileLabel1.setObjectName("dashFileLabel1")
        self.dashBrowseBtn1_2 = QtWidgets.QPushButton(self.frame)
        self.dashBrowseBtn1_2.setGeometry(QtCore.QRect(790, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dashBrowseBtn1_2.setFont(font)
        self.dashBrowseBtn1_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.dashBrowseBtn1_2.setObjectName("dashBrowseBtn1_2")
        self.dashTimeText_3 = QtWidgets.QLabel(self.frame)
        self.dashTimeText_3.setGeometry(QtCore.QRect(630, 310, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashTimeText_3.setFont(font)
        self.dashTimeText_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.dashTimeText_3.setObjectName("dashTimeText_3")
        self.dashTimeText_2 = QtWidgets.QLabel(self.frame)
        self.dashTimeText_2.setGeometry(QtCore.QRect(630, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dashTimeText_2.setFont(font)
        self.dashTimeText_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.dashTimeText_2.setObjectName("dashTimeText_2")
        self.dashTimeText_4 = QtWidgets.QLabel(self.frame)
        self.dashTimeText_4.setGeometry(QtCore.QRect(630, 270, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dashTimeText_4.setFont(font)
        self.dashTimeText_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.dashTimeText_4.setObjectName("dashTimeText_4")
        self.dashErrorLabel = QtWidgets.QLabel(self.frame)
        self.dashErrorLabel.setGeometry(QtCore.QRect(130, 700, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dashErrorLabel.setFont(font)
        self.dashErrorLabel.setStyleSheet("\n"
"color: rgb(255, 0, 0);")
        self.dashErrorLabel.setText("")
        self.dashErrorLabel.setObjectName("dashErrorLabel")
        self.dashWeightPortList = QtWidgets.QComboBox(self.frame)
        self.dashWeightPortList.setGeometry(QtCore.QRect(760, 650, 111, 31))
        self.dashWeightPortList.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.dashWeightPortList.setEditable(False)
        self.dashWeightPortList.setObjectName("dashWeightPortList")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(600, 680, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.dashBrowseBtn3 = QtWidgets.QPushButton(self.frame)
        self.dashBrowseBtn3.setGeometry(QtCore.QRect(790, 390, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dashBrowseBtn3.setFont(font)
        self.dashBrowseBtn3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.dashBrowseBtn3.setObjectName("dashBrowseBtn3")
        self.dashTimeText_5 = QtWidgets.QLabel(self.frame)
        self.dashTimeText_5.setGeometry(QtCore.QRect(630, 350, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.dashTimeText_5.setFont(font)
        self.dashTimeText_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.dashTimeText_5.setObjectName("dashTimeText_5")
        self.dashFileLabel3 = QtWidgets.QLabel(self.frame)
        self.dashFileLabel3.setGeometry(QtCore.QRect(630, 390, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashFileLabel3.setFont(font)
        self.dashFileLabel3.setStyleSheet("color: rgb(0 0,0);\n"
"background-color: rgb(255, 170, 127);")
        self.dashFileLabel3.setObjectName("dashFileLabel3")
        self.dashAboutBtn = QtWidgets.QPushButton(self.frame)
        self.dashAboutBtn.setGeometry(QtCore.QRect(740, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dashAboutBtn.setFont(font)
        self.dashAboutBtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.dashAboutBtn.setObjectName("dashAboutBtn")
        self.dashBtn1.raise_()
        self.label_6.raise_()
        self.dashUserNameText.raise_()
        self.dashDateText.raise_()
        self.dashTimeText.raise_()
        self.titleText.raise_()
        self.dashBtn2.raise_()
        self.dashBtn3.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.rfidStatLabel.raise_()
        self.weighScaleStatLabel.raise_()
        self.dashLogoutBtn.raise_()
        self.dashReconnectBtn.raise_()
        self.dashBrowseBtn1.raise_()
        self.dashFileLabel1.raise_()
        self.dashBrowseBtn1_2.raise_()
        self.dashTimeText_3.raise_()
        self.dashTimeText_2.raise_()
        self.dashTimeText_4.raise_()
        self.dashErrorLabel.raise_()
        self.dashWeightPortList.raise_()
        self.label_18.raise_()
        self.dashBrowseBtn3.raise_()
        self.dashTimeText_5.raise_()
        self.dashFileLabel3.raise_()
        self.dashAboutBtn.raise_()
        self.stackedWidget.addWidget(self.dashboardPage)
        self.CreateShipment = QtWidgets.QWidget()
        self.CreateShipment.setObjectName("CreateShipment")
        self.frame_2 = QtWidgets.QFrame(self.CreateShipment)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 901, 801))
        self.frame_2.setStyleSheet("background-color: rgb(6, 118, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(220, 70, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(60, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(60, 230, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(400, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(70, 300, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(70, 340, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(70, 380, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.CS_dateInput = QtWidgets.QLineEdit(self.frame_2)
        self.CS_dateInput.setGeometry(QtCore.QRect(150, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CS_dateInput.setFont(font)
        self.CS_dateInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CS_dateInput.setText("")
        self.CS_dateInput.setObjectName("CS_dateInput")
        self.CS_timeInput = QtWidgets.QLineEdit(self.frame_2)
        self.CS_timeInput.setGeometry(QtCore.QRect(150, 230, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CS_timeInput.setFont(font)
        self.CS_timeInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CS_timeInput.setText("")
        self.CS_timeInput.setObjectName("CS_timeInput")
        self.CS_binNoInput = QtWidgets.QLineEdit(self.frame_2)
        self.CS_binNoInput.setGeometry(QtCore.QRect(490, 180, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CS_binNoInput.setFont(font)
        self.CS_binNoInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CS_binNoInput.setText("")
        self.CS_binNoInput.setObjectName("CS_binNoInput")
        self.CS_emptyWeightInput = QtWidgets.QLineEdit(self.frame_2)
        self.CS_emptyWeightInput.setGeometry(QtCore.QRect(260, 300, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CS_emptyWeightInput.setFont(font)
        self.CS_emptyWeightInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CS_emptyWeightInput.setText("")
        self.CS_emptyWeightInput.setObjectName("CS_emptyWeightInput")
        self.CS_totalWeightInput = QtWidgets.QLineEdit(self.frame_2)
        self.CS_totalWeightInput.setGeometry(QtCore.QRect(260, 340, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CS_totalWeightInput.setFont(font)
        self.CS_totalWeightInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CS_totalWeightInput.setText("")
        self.CS_totalWeightInput.setObjectName("CS_totalWeightInput")
        self.CS_netWeightLabel = QtWidgets.QLabel(self.frame_2)
        self.CS_netWeightLabel.setGeometry(QtCore.QRect(260, 380, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CS_netWeightLabel.setFont(font)
        self.CS_netWeightLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.CS_netWeightLabel.setText("")
        self.CS_netWeightLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CS_netWeightLabel.setObjectName("CS_netWeightLabel")
        self.CS_createBtn = QtWidgets.QPushButton(self.frame_2)
        self.CS_createBtn.setGeometry(QtCore.QRect(260, 450, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.CS_createBtn.setFont(font)
        self.CS_createBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.CS_createBtn.setObjectName("CS_createBtn")
        self.CS_statusLabel = QtWidgets.QLabel(self.frame_2)
        self.CS_statusLabel.setGeometry(QtCore.QRect(110, 520, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CS_statusLabel.setFont(font)
        self.CS_statusLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.CS_statusLabel.setObjectName("CS_statusLabel")
        self.CS_statusBar = QtWidgets.QProgressBar(self.frame_2)
        self.CS_statusBar.setGeometry(QtCore.QRect(590, 520, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CS_statusBar.setFont(font)
        self.CS_statusBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.CS_statusBar.setProperty("value", 0)
        self.CS_statusBar.setTextVisible(True)
        self.CS_statusBar.setObjectName("CS_statusBar")
        self.CS_backBtn = QtWidgets.QPushButton(self.frame_2)
        self.CS_backBtn.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CS_backBtn.setFont(font)
        self.CS_backBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.CS_backBtn.setObjectName("CS_backBtn")
        self.stackedWidget.addWidget(self.CreateShipment)
        self.VerifyShipmentPage = QtWidgets.QWidget()
        self.VerifyShipmentPage.setObjectName("VerifyShipmentPage")
        self.frame_3 = QtWidgets.QFrame(self.VerifyShipmentPage)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 901, 811))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.frame_3.setFont(font)
        self.frame_3.setStyleSheet("background-color: rgb(6, 118, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(5)
        self.frame_3.setObjectName("frame_3")
        self.VS_backBtn = QtWidgets.QPushButton(self.frame_3)
        self.VS_backBtn.setGeometry(QtCore.QRect(10, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.VS_backBtn.setFont(font)
        self.VS_backBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.VS_backBtn.setObjectName("VS_backBtn")
        self.VS_invoiceInput = QtWidgets.QLineEdit(self.frame_3)
        self.VS_invoiceInput.setGeometry(QtCore.QRect(170, 110, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.VS_invoiceInput.setFont(font)
        self.VS_invoiceInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VS_invoiceInput.setText("")
        self.VS_invoiceInput.setObjectName("VS_invoiceInput")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(220, 30, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(40, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.VS_searchBtn = QtWidgets.QPushButton(self.frame_3)
        self.VS_searchBtn.setGeometry(QtCore.QRect(340, 110, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.VS_searchBtn.setFont(font)
        self.VS_searchBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.VS_searchBtn.setObjectName("VS_searchBtn")
        self.line = QtWidgets.QFrame(self.frame_3)
        self.line.setGeometry(QtCore.QRect(30, 160, 841, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setStyleSheet("color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));")
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(6)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.VS_searchErrorLabel = QtWidgets.QLabel(self.frame_3)
        self.VS_searchErrorLabel.setGeometry(QtCore.QRect(220, 490, 471, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.VS_searchErrorLabel.setFont(font)
        self.VS_searchErrorLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.VS_searchErrorLabel.setText("")
        self.VS_searchErrorLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.VS_searchErrorLabel.setObjectName("VS_searchErrorLabel")
        self.line_2 = QtWidgets.QFrame(self.frame_3)
        self.line_2.setGeometry(QtCore.QRect(30, 520, 841, 16))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.line_2.setFont(font)
        self.line_2.setStyleSheet("color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 255), stop:0.19397 rgba(0, 0, 0, 255), stop:0.202312 rgba(122, 97, 0, 255), stop:0.495514 rgba(76, 58, 0, 255), stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(6)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.VS_weighBtn = QtWidgets.QPushButton(self.frame_3)
        self.VS_weighBtn.setGeometry(QtCore.QRect(720, 620, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.VS_weighBtn.setFont(font)
        self.VS_weighBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.VS_weighBtn.setObjectName("VS_weighBtn")
        self.VS_weighInput = QtWidgets.QLineEdit(self.frame_3)
        self.VS_weighInput.setGeometry(QtCore.QRect(570, 620, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.VS_weighInput.setFont(font)
        self.VS_weighInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VS_weighInput.setText("")
        self.VS_weighInput.setReadOnly(True)
        self.VS_weighInput.setObjectName("VS_weighInput")
        self.label_31 = QtWidgets.QLabel(self.frame_3)
        self.label_31.setGeometry(QtCore.QRect(450, 620, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_3)
        self.label_32.setGeometry(QtCore.QRect(70, 620, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.VS_RFIDInput = QtWidgets.QLineEdit(self.frame_3)
        self.VS_RFIDInput.setGeometry(QtCore.QRect(190, 620, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.VS_RFIDInput.setFont(font)
        self.VS_RFIDInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VS_RFIDInput.setText("")
        self.VS_RFIDInput.setReadOnly(True)
        self.VS_RFIDInput.setObjectName("VS_RFIDInput")
        self.VS_RFIDDetectBtn = QtWidgets.QPushButton(self.frame_3)
        self.VS_RFIDDetectBtn.setGeometry(QtCore.QRect(340, 620, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.VS_RFIDDetectBtn.setFont(font)
        self.VS_RFIDDetectBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.VS_RFIDDetectBtn.setObjectName("VS_RFIDDetectBtn")
        self.VS_verifyShipmentBtn = QtWidgets.QPushButton(self.frame_3)
        self.VS_verifyShipmentBtn.setGeometry(QtCore.QRect(360, 550, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.VS_verifyShipmentBtn.setFont(font)
        self.VS_verifyShipmentBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.VS_verifyShipmentBtn.setObjectName("VS_verifyShipmentBtn")
        self.VS_resultTab = QtWidgets.QStackedWidget(self.frame_3)
        self.VS_resultTab.setGeometry(QtCore.QRect(110, 700, 711, 41))
        self.VS_resultTab.setStyleSheet("background-color: rgb(6, 118, 255);")
        self.VS_resultTab.setObjectName("VS_resultTab")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.VS_resultTab.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.VS_printLabelBtn = QtWidgets.QPushButton(self.page_3)
        self.VS_printLabelBtn.setGeometry(QtCore.QRect(560, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.VS_printLabelBtn.setFont(font)
        self.VS_printLabelBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.VS_printLabelBtn.setObjectName("VS_printLabelBtn")
        self.VS_resultTab.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.VS_progress = QtWidgets.QProgressBar(self.page_4)
        self.VS_progress.setGeometry(QtCore.QRect(240, 10, 241, 23))
        self.VS_progress.setProperty("value", 20)
        self.VS_progress.setObjectName("VS_progress")
        self.VS_resultTab.addWidget(self.page_4)
        self.VS_ErrorLabel_2 = QtWidgets.QLabel(self.frame_3)
        self.VS_ErrorLabel_2.setGeometry(QtCore.QRect(190, 750, 561, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.VS_ErrorLabel_2.setFont(font)
        self.VS_ErrorLabel_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.VS_ErrorLabel_2.setText("")
        self.VS_ErrorLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.VS_ErrorLabel_2.setObjectName("VS_ErrorLabel_2")
        self.invoiceTable = QtWidgets.QTableWidget(self.frame_3)
        self.invoiceTable.setGeometry(QtCore.QRect(30, 180, 841, 301))
        self.invoiceTable.setMinimumSize(QtCore.QSize(750, 0))
        self.invoiceTable.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.invoiceTable.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.invoiceTable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.invoiceTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.invoiceTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.invoiceTable.setShowGrid(True)
        self.invoiceTable.setCornerButtonEnabled(True)
        self.invoiceTable.setColumnCount(7)
        self.invoiceTable.setObjectName("invoiceTable")
        self.invoiceTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.invoiceTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.invoiceTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.invoiceTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.invoiceTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.invoiceTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.invoiceTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.invoiceTable.setHorizontalHeaderItem(6, item)
        self.invoiceTable.horizontalHeader().setVisible(False)
        self.invoiceTable.horizontalHeader().setCascadingSectionResizes(True)
        self.invoiceTable.horizontalHeader().setHighlightSections(True)
        self.invoiceTable.horizontalHeader().setStretchLastSection(True)
        self.invoiceTable.verticalHeader().setCascadingSectionResizes(True)
        self.label_45 = QtWidgets.QLabel(self.frame_3)
        self.label_45.setGeometry(QtCore.QRect(620, 110, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.VS_dateInput = QtWidgets.QLineEdit(self.frame_3)
        self.VS_dateInput.setGeometry(QtCore.QRect(740, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.VS_dateInput.setFont(font)
        self.VS_dateInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VS_dateInput.setText("")
        self.VS_dateInput.setReadOnly(True)
        self.VS_dateInput.setObjectName("VS_dateInput")
        self.VS_clearBtn = QtWidgets.QPushButton(self.frame_3)
        self.VS_clearBtn.setGeometry(QtCore.QRect(440, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.VS_clearBtn.setFont(font)
        self.VS_clearBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.VS_clearBtn.setObjectName("VS_clearBtn")
        self.label_33 = QtWidgets.QLabel(self.frame_3)
        self.label_33.setGeometry(QtCore.QRect(70, 650, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.VS_binNoInput = QtWidgets.QLineEdit(self.frame_3)
        self.VS_binNoInput.setGeometry(QtCore.QRect(190, 650, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.VS_binNoInput.setFont(font)
        self.VS_binNoInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VS_binNoInput.setText("")
        self.VS_binNoInput.setReadOnly(True)
        self.VS_binNoInput.setObjectName("VS_binNoInput")
        self.label_34 = QtWidgets.QLabel(self.frame_3)
        self.label_34.setGeometry(QtCore.QRect(450, 650, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.VS_emptyBinWeighInput = QtWidgets.QLineEdit(self.frame_3)
        self.VS_emptyBinWeighInput.setGeometry(QtCore.QRect(570, 650, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.VS_emptyBinWeighInput.setFont(font)
        self.VS_emptyBinWeighInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.VS_emptyBinWeighInput.setText("")
        self.VS_emptyBinWeighInput.setReadOnly(True)
        self.VS_emptyBinWeighInput.setObjectName("VS_emptyBinWeighInput")
        self.stackedWidget.addWidget(self.VerifyShipmentPage)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.frame_4 = QtWidgets.QFrame(self.page_5)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 901, 791))
        self.frame_4.setStyleSheet("background-color: rgb(6, 118, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setGeometry(QtCore.QRect(190, 110, 571, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_20.setObjectName("label_20")
        self.label_23 = QtWidgets.QLabel(self.frame_4)
        self.label_23.setGeometry(QtCore.QRect(190, 180, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_23.setWordWrap(True)
        self.label_23.setObjectName("label_23")
        self.about_backbtn = QtWidgets.QPushButton(self.frame_4)
        self.about_backbtn.setGeometry(QtCore.QRect(20, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.about_backbtn.setFont(font)
        self.about_backbtn.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(101, 116, 58);")
        self.about_backbtn.setObjectName("about_backbtn")
        self.stackedWidget.addWidget(self.page_5)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame_5 = QtWidgets.QFrame(self.page)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 901, 801))
        self.frame_5.setStyleSheet("background-color: rgb(6, 118, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(5)
        self.frame_5.setObjectName("frame_5")
        self.HS_tableView = QtWidgets.QTableWidget(self.frame_5)
        self.HS_tableView.setGeometry(QtCore.QRect(30, 380, 841, 321))
        self.HS_tableView.setMinimumSize(QtCore.QSize(750, 0))
        self.HS_tableView.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.HS_tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HS_tableView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HS_tableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.HS_tableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.HS_tableView.setShowGrid(True)
        self.HS_tableView.setCornerButtonEnabled(True)
        self.HS_tableView.setColumnCount(7)
        self.HS_tableView.setObjectName("HS_tableView")
        self.HS_tableView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.HS_tableView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HS_tableView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HS_tableView.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HS_tableView.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HS_tableView.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.HS_tableView.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.HS_tableView.setHorizontalHeaderItem(6, item)
        self.HS_tableView.horizontalHeader().setVisible(False)
        self.HS_tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.HS_tableView.horizontalHeader().setHighlightSections(True)
        self.HS_tableView.horizontalHeader().setStretchLastSection(True)
        self.HS_tableView.verticalHeader().setCascadingSectionResizes(True)
        self.HS_backBtn = QtWidgets.QPushButton(self.frame_5)
        self.HS_backBtn.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.HS_backBtn.setFont(font)
        self.HS_backBtn.setStyleSheet("background-color: rgb(101, 116, 58);\n"
"color: rgb(255, 255, 255);")
        self.HS_backBtn.setObjectName("HS_backBtn")
        self.HS_listView = QtWidgets.QListWidget(self.frame_5)
        self.HS_listView.setGeometry(QtCore.QRect(100, 80, 701, 271))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.HS_listView.setFont(font)
        self.HS_listView.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(85, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.HS_listView.setFrameShape(QtWidgets.QFrame.Box)
        self.HS_listView.setLineWidth(5)
        self.HS_listView.setObjectName("HS_listView")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(280, 10, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.HS_binNoInput = QtWidgets.QLineEdit(self.frame_5)
        self.HS_binNoInput.setGeometry(QtCore.QRect(160, 720, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.HS_binNoInput.setFont(font)
        self.HS_binNoInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HS_binNoInput.setText("")
        self.HS_binNoInput.setReadOnly(True)
        self.HS_binNoInput.setObjectName("HS_binNoInput")
        self.label_46 = QtWidgets.QLabel(self.frame_5)
        self.label_46.setGeometry(QtCore.QRect(40, 720, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.frame_5)
        self.label_47.setGeometry(QtCore.QRect(580, 720, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_47.setObjectName("label_47")
        self.HS_seqNoInput = QtWidgets.QLineEdit(self.frame_5)
        self.HS_seqNoInput.setGeometry(QtCore.QRect(660, 720, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.HS_seqNoInput.setFont(font)
        self.HS_seqNoInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HS_seqNoInput.setText("")
        self.HS_seqNoInput.setReadOnly(True)
        self.HS_seqNoInput.setObjectName("HS_seqNoInput")
        self.label_50 = QtWidgets.QLabel(self.frame_5)
        self.label_50.setGeometry(QtCore.QRect(290, 720, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.HS_emptyWeighInput = QtWidgets.QLineEdit(self.frame_5)
        self.HS_emptyWeighInput.setGeometry(QtCore.QRect(450, 720, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.HS_emptyWeighInput.setFont(font)
        self.HS_emptyWeighInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HS_emptyWeighInput.setText("")
        self.HS_emptyWeighInput.setReadOnly(True)
        self.HS_emptyWeighInput.setObjectName("HS_emptyWeighInput")
        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.Body)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.VS_resultTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DANA Dispatcher "))
        self.LoginLayout.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "LOGIN"))
        self.label_2.setText(_translate("MainWindow", "UserID: "))
        self.label_3.setText(_translate("MainWindow", "Password: "))
        self.loginBtn.setText(_translate("MainWindow", "LOGIN"))
        self.dashUserNameText.setText(_translate("MainWindow", "User1"))
        self.dashDateText.setText(_translate("MainWindow", "12 March 2023"))
        self.dashTimeText.setText(_translate("MainWindow", "12:45 PM"))
        self.titleText.setText(_translate("MainWindow", "SHIPMENT DISPATCH MANAGEMENT SYSTEM"))
        self.dashBtn1.setText(_translate("MainWindow", "Create A Shipment"))
        self.dashBtn2.setText(_translate("MainWindow", "Verify Shipment"))
        self.dashBtn3.setText(_translate("MainWindow", "History"))
        self.label_7.setText(_translate("MainWindow", "RFID Scanner Status: "))
        self.label_8.setText(_translate("MainWindow", "Weigh Scale PORT: "))
        self.rfidStatLabel.setText(_translate("MainWindow", "Connected"))
        self.weighScaleStatLabel.setText(_translate("MainWindow", "NOT CONNECTED"))
        self.dashLogoutBtn.setText(_translate("MainWindow", "LOGOUT"))
        self.dashReconnectBtn.setText(_translate("MainWindow", "RECONNECT"))
        self.dashBrowseBtn1.setText(_translate("MainWindow", "Browse"))
        self.dashFileLabel1.setText(_translate("MainWindow", "Choose File.."))
        self.dashBrowseBtn1_2.setText(_translate("MainWindow", "Browse"))
        self.dashTimeText_3.setText(_translate("MainWindow", "Choose File.."))
        self.dashTimeText_2.setText(_translate("MainWindow", "Master Data:"))
        self.dashTimeText_4.setText(_translate("MainWindow", "Invoice Data:"))
        self.label_18.setText(_translate("MainWindow", "Weigh Scale Status: "))
        self.dashBrowseBtn3.setText(_translate("MainWindow", "Browse"))
        self.dashTimeText_5.setText(_translate("MainWindow", "Bin Data: "))
        self.dashFileLabel3.setText(_translate("MainWindow", "Choose File.."))
        self.dashAboutBtn.setText(_translate("MainWindow", "ABOUT"))
        self.label_9.setText(_translate("MainWindow", "Create Shipment"))
        self.label_10.setText(_translate("MainWindow", "Date: "))
        self.label_11.setText(_translate("MainWindow", "Time: "))
        self.label_12.setText(_translate("MainWindow", "Bin No. : "))
        self.label_13.setText(_translate("MainWindow", "Bin Empty Weight: "))
        self.label_14.setText(_translate("MainWindow", "Bin Total Weight: "))
        self.label_15.setText(_translate("MainWindow", "Bin Net Weight: "))
        self.CS_emptyWeightInput.setPlaceholderText(_translate("MainWindow", "Grams"))
        self.CS_totalWeightInput.setPlaceholderText(_translate("MainWindow", "Grams"))
        self.CS_createBtn.setText(_translate("MainWindow", "Create Shipment"))
        self.CS_statusLabel.setText(_translate("MainWindow", "Please Place RFID TAG To Scanner"))
        self.CS_backBtn.setText(_translate("MainWindow", "< Back"))
        self.VS_backBtn.setText(_translate("MainWindow", "< Back"))
        self.label_16.setText(_translate("MainWindow", "Verify Shipment"))
        self.label_17.setText(_translate("MainWindow", "Invoice No. :"))
        self.VS_searchBtn.setText(_translate("MainWindow", "SEARCH"))
        self.VS_weighBtn.setText(_translate("MainWindow", "WEIGH "))
        self.label_31.setText(_translate("MainWindow", "Weigh Bin:"))
        self.label_32.setText(_translate("MainWindow", "RFID Tag ID: "))
        self.VS_RFIDDetectBtn.setText(_translate("MainWindow", "DETECT"))
        self.VS_verifyShipmentBtn.setText(_translate("MainWindow", "Verify Shipment"))
        self.VS_printLabelBtn.setText(_translate("MainWindow", "Print Label"))
        self.invoiceTable.setSortingEnabled(False)
        item = self.invoiceTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PartName"))
        item = self.invoiceTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PartDescription"))
        item = self.invoiceTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NetWeight"))
        item = self.invoiceTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TotalQuantity"))
        item = self.invoiceTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "DispatchQty"))
        item = self.invoiceTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "BalQuantity"))
        item = self.invoiceTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "TotalWeight"))
        self.label_45.setText(_translate("MainWindow", "Invoice Date: "))
        self.VS_clearBtn.setText(_translate("MainWindow", "CLEAR"))
        self.label_33.setText(_translate("MainWindow", "Bin No:"))
        self.label_34.setText(_translate("MainWindow", "Empty Bin Weigh:"))
        self.label_20.setText(_translate("MainWindow", "OPEN-SOURCE, FREE TO USE:"))
        self.label_23.setText(_translate("MainWindow", "-DEVELOPED BY: SHADAB KN."))
        self.about_backbtn.setText(_translate("MainWindow", "< BACK"))
        self.HS_tableView.setSortingEnabled(False)
        item = self.HS_tableView.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "PartName"))
        item = self.HS_tableView.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "PartDescription"))
        item = self.HS_tableView.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NetWeight"))
        item = self.HS_tableView.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TotalQuantity"))
        item = self.HS_tableView.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "DispatchQty"))
        item = self.HS_tableView.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "BalQuantity"))
        item = self.HS_tableView.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "TotalWeight"))
        self.HS_backBtn.setText(_translate("MainWindow", "< Back"))
        self.label_24.setText(_translate("MainWindow", "HISTORY"))
        self.label_46.setText(_translate("MainWindow", "Bin No:"))
        self.label_47.setText(_translate("MainWindow", "Seq No:"))
        self.label_50.setText(_translate("MainWindow", "Empty Bin Weigh:"))
import app_rsc_rc
